baseURL = 'https://yuanshuai1122.github.io/'
languageCode = 'zh-hans'
defaultContentLanguage = "zh-hans"
hasCJKLanguage = true
enableEmoji = true
title = '🧀'
copyright = 'yuanshuai'
theme = 'hugo-theme-itheme'
paginate = 10
[params]
  defaultCover = 'https://www.apple.com.cn/newsroom/images/apple-logo_black.jpg.landing-regular_2x.jpg'
  email = 'shuaiyuan@gmail.com'
  [[params.socialMedia]]
    name = 'Github'
    url = 'https://github.com/yuanshuai1122'
  [[params.blogroll]]
    name = '👋'
    url = 'https://yuanshuaicn.com/'
