name: Update Theme

on:
  workflow_dispatch:
  repository_dispatch:
    types: UpdateTheme
    
jobs:
  update_theme:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Git Sumbodule Update
      run: |
        git pull --recurse-submodules
        git submodule update --remote --recursive

    - name: Commit update
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git add --all
        git commit -m "Update theme automatically" && git push|| echo "No changes to commit"
